server {
    listen 80 default_server;
    server_name _;

    server_tokens off;

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://backend:8000/api/;
    }

    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://backend:8000/admin/;
    }

    location ^~ /static/admin/ {
        alias /static/admin/;
    }

    location /static/ {
        proxy_set_header Host $http_host;
        proxy_pass http://frontend:8000;
    }

    location /media/ {
        alias /media/;
    }

    # Все маршруты React: /, /signin, /signup и т. д.
    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_intercept_errors on;
        error_page 404 = /__spa_index;
        proxy_pass http://frontend:8000;
    }

    # Внутренний запрос к корню frontend, который отдаёт index.html.
    location = /__spa_index {
        internal;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://frontend:8000/;
    }
}
